package pl.humberd.salary_comparator.ui.components

import android.content.Context
import com.murgupluoglu.flagkit.FlagKit

data class Currency(
    val id: String,
    val name: String,
    val flagCode: String,
) {
    private var to1EuroRate: Double = -1.0

    fun updateRate(rate: Double) {
        to1EuroRate = rate
    }

    fun getRate(): Double {
        return to1EuroRate
    }

    fun getFlagId(context: Context): Int? {
        return FlagKit.getResId(context, flagCode).let {
            if (it == 0) {
                return@let null
            }
            it
        }
    }
}

val CURRENCIES = listOf(
    Currency("aed", "United Arab Emirates Dirham", "ae"),
    Currency("afn", "Afghan afghani", "af"),
    Currency("all", "Albanian lek", "al"),
    Currency("amd", "Armenian dram", "am"),
    Currency("ang", "Netherlands Antillean Guilder", "nl"),
    Currency("aoa", "Angolan kwanza", "ao"),
    Currency("ars", "Argentine peso", "ar"),
    Currency("aud", "Australian dollar", "au"),
    Currency("awg", "Aruban florin", "aw"),
    Currency("azn", "Azerbaijani manat", "az"),
    Currency("bam", "Bosnia-Herzegovina Convertible Mark", "ba"),
    Currency("bbd", "Bajan dollar", "bb"),
    Currency("bch", "Bitcoin Cash", "bch"),
    Currency("bdt", "Bangladeshi taka", "bd"),
    Currency("bgn", "Bulgarian lev", "bg"),
    Currency("bhd", "Bahraini dinar", "bh"),
    Currency("bif", "Burundian Franc", "bi"),
    Currency("bmd", "Bermudan dollar", "bm"),
    Currency("bnd", "Brunei dollar", "bn"),
    Currency("bob", "Bolivian boliviano", "bo"),
    Currency("brl", "Brazilian real", "br"),
    Currency("bsd", "Bahamian dollar", "bs"),
    Currency("btn", "Bhutan currency", "bt"),
    Currency("bwp", "Botswanan Pula", "bw"),
    Currency("byn", "Belarusian Ruble", "by"),
    Currency("bzd", "Belize dollar", "bz"),
    Currency("cad", "Canadian dollar", "ca"),
    Currency("cdf", "Congolese franc", "cd"),
    Currency("chf", "Swiss franc", "ch"),
    Currency("clf", "Chilean Unit of Account (UF)", "cl"),
    Currency("clp", "Chilean peso", "cl"),
    Currency("cnh", "Chinese Yuan (offshore)", "cn"),
    Currency("cny", "Chinese Yuan", "cn"),
    Currency("cop", "Colombian peso", "co"),
    Currency("crc", "Costa Rican Colón", "cr"),
    Currency("cup", "Cuban Peso", "cu"),
    Currency("cve", "Cape Verdean escudo", "cv"),
    Currency("czk", "Czech koruna", "cz"),
    Currency("djf", "Djiboutian franc", "dj"),
    Currency("dkk", "Danish krone", "dk"),
    Currency("dop", "Dominican peso", "do"),
    Currency("dzd", "Algerian dinar", "dz"),
    Currency("eek", "Estonian kroon", "ee"),
    Currency("egp", "Egyptian pound", "eg"),
    Currency("ern", "Eritrean nakfa", "er"),
    Currency("etb", "Ethiopian birr", "et"),
    Currency("eth", "Ether", "et"),
    Currency("eur", "Euro", "eu"),
    Currency("fjd", "Fijian dollar", "fj"),
    Currency("gbp", "Pound sterling", "gb"),
    Currency("gel", "Georgian lari", "ge"),
    Currency("ghs", "Ghanaian cedi", "gh"),
    Currency("gip", "Gibraltar pound", "gi"),
    Currency("gmd", "Gambian dalasi", "gm"),
    Currency("gnf", "Guinean franc", "gn"),
    Currency("gqe", "Central African CFA franc", "gq"),
    Currency("gtq", "Guatemalan quetzal", "gt"),
    Currency("gyd", "Guyanaese Dollar", "gy"),
    Currency("hkd", "Hong Kong dollar", "hk"),
    Currency("hnl", "Honduran lempira", "hn"),
    Currency("hrk", "Croatian kuna", "hr"),
    Currency("htg", "Haitian gourde", "ht"),
    Currency("huf", "Hungarian forint", "hu"),
    Currency("idr", "Indonesian rupiah", "id"),
    Currency("ils", "Israeli New Shekel", "il"),
    Currency("inr", "Indian rupee", "in"),
    Currency("iqd", "Iraqi dinar", "iq"),
    Currency("irr", "Iranian rial", "ir"),
    Currency("isk", "Icelandic króna", "is"),
    Currency("jmd", "Jamaican dollar", "jm"),
    Currency("jod", "Jordanian dinar", "jo"),
    Currency("jpy", "Japanese yen", "jp"),
    Currency("kes", "Kenyan shilling", "ke"),
    Currency("kgs", "Kyrgystani Som", "kg"),
    Currency("khr", "Cambodian riel", "kh"),
    Currency("kmf", "Comorian franc", "km"),
    Currency("kpw", "North Korean won", "kp"),
    Currency("krw", "South Korean won", "kr"),
    Currency("kwd", "Kuwaiti dinar", "kw"),
    Currency("kyd", "Cayman Islands dollar", "ky"),
    Currency("kzt", "Kazakhstani tenge", "kz"),
    Currency("lak", "Laotian Kip", "la"),
    Currency("lbp", "Lebanese pound", "lb"),
    Currency("lkr", "Sri Lankan rupee", "lk"),
    Currency("lrd", "Liberian dollar", "lr"),
    Currency("lsl", "Lesotho loti", "ls"),
    Currency("ltc", "Litecoin", "lt"),
    Currency("lyd", "Libyan dinar", "ly"),
    Currency("mad", "Moroccan dirham", "ma"),
    Currency("mdl", "Moldovan leu", "md"),
    Currency("mga", "Malagasy ariary", "mg"),
    Currency("mkd", "Macedonian denar", "mk"),
    Currency("mmk", "Myanmar Kyat", "mm"),
    Currency("mnt", "Mongolian tugrik", "mn"),
    Currency("mop", "Macanese pataca", "mo"),
    Currency("mru", "Mauritanian Ouguiya (1973–2017)", "mr"),
    Currency("mur", "Mauritian rupee", "mu"),
    Currency("mvr", "Maldivian rufiyaa", "mv"),
    Currency("mwk", "Malawian kwacha", "mw"),
    Currency("mxn", "Mexican peso", "mx"),
    Currency("myr", "Malaysian ringgit", "my"),
    Currency("mzm", "Mozambican metical", "mz"),
    Currency("nad", "Namibian dollar", "na"),
    Currency("ngn", "Nigerian naira", "ng"),
    Currency("nio", "Nicaraguan córdoba", "ni"),
    Currency("nok", "Norwegian krone", "no"),
    Currency("npr", "Nepalese rupee", "np"),
    Currency("nzd", "New Zealand dollar", "nz"),
    Currency("omr", "Omani rial", "om"),
    Currency("pab", "Panamanian balboa", "pa"),
    Currency("pen", "Sol", "pe"),
    Currency("pgk", "Papua New Guinean kina", "pg"),
    Currency("php", "Philippine peso", "ph"),
    Currency("pkr", "Pakistani rupee", "pk"),
    Currency("pln", "Poland złoty", "pl"),
    Currency("pyg", "Paraguayan guarani", "py"),
    Currency("qar", "Qatari Rial", "qa"),
    Currency("ron", "Romanian leu", "ro"),
    Currency("rsd", "Serbian dinar", "rs"),
    Currency("rub", "Russian ruble", "ru"),
    Currency("rwf", "Rwandan Franc", "rw"),
    Currency("sar", "Saudi riyal", "sa"),
    Currency("sbd", "Solomon Islands dollar", "sb"),
    Currency("scr", "Seychellois rupee", "sc"),
    Currency("sdg", "Sudanese pound", "sd"),
    Currency("sek", "Swedish krona", "se"),
    Currency("sgd", "Singapore dollar", "sg"),
    Currency("shp", "Saint Helena pound", "sh"),
    Currency("sll", "Sierra Leonean leone", "sl"),
    Currency("sos", "Somali shilling", "so"),
    Currency("srd", "Surinamese dollar", "sr"),
    Currency("ssp", "South Sudanese Pound", "ss"),
    Currency("std", "São Tomé and Príncipe Dobra (pre-2018)", "st"),
    Currency("stn", "Steneum Coin", "st"),
    Currency("svc", "Salvadoran Colón", "sv"),
    Currency("syp", "Syrian pound", "sy"),
    Currency("szl", "Swazi lilangeni", "sz"),
    Currency("thb", "Thai baht", "th"),
    Currency("tjs", "Tajikistani somoni", "tj"),
    Currency("tmt", "Turkmenistani manat", "tm"),
    Currency("tnd", "Tunisian dinar", "tn"),
    Currency("top", "Tongan Paʻanga", "to"),
    Currency("try", "Turkish lira", "tr"),
    Currency("ttd", "Trinidad & Tobago Dollar", "tt"),
    Currency("twd", "New Taiwan dollar", "tw"),
    Currency("tzs", "Tanzanian shilling", "tz"),
    Currency("uah", "Ukrainian hryvnia", "ua"),
    Currency("ugx", "Ugandan shilling", "ug"),
    Currency("usd", "United States dollar", "us"),
    Currency("uyu", "Uruguayan peso", "uy"),
    Currency("uzs", "Uzbekistani som", "uz"),
    Currency("vef", "Sovereign Bolivar", "ve"),
    Currency("vnd", "Vietnamese dong", "vn"),
    Currency("vuv", "Vanuatu vatu", "vu"),
    Currency("wst", "Samoan tala", "ws"),
    Currency("xaf", "Central African CFA franc", "cf"),
    Currency("xcd", "East Caribbean dollar", "gd"),
    Currency("xof", "West African CFA franc", "ne"),
    Currency("yer", "Yemeni rial", "ye"),
    Currency("zar", "South African rand", "za"),
    Currency("zmw", "Zambian Kwacha", "zm")
)
