package pl.humberd.salary_comparator.services

import android.content.Context
import androidx.annotation.StringRes
import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import com.murgupluoglu.flagkit.FlagKit
import pl.humberd.salary_comparator.R

data class Currency(
    val id: String,
    @StringRes private val nameRes: Int,
    val flagCode: String,
) {
    private var to1EuroRate: Double = -1.0

    @Composable
    fun getName() = stringResource(nameRes)

    fun getName(context: Context) = context.getString(nameRes)

    fun updateRate(rate: Double) {
        to1EuroRate = rate
    }

    fun getRate(): Double {
        return to1EuroRate
    }

    fun getFlagId(context: Context): Int? {
        return FlagKit.getResId(context, flagCode).let {
            if (it == 0) {
                return@let null
            }
            it
        }
    }
}

val CURRENCIES = listOf(
    Currency("aed", R.string.currency_country_aed, "ae"),
    Currency("afn", R.string.currency_country_afn, "af"),
    Currency("all", R.string.currency_country_all, "al"),
    Currency("amd", R.string.currency_country_amd, "am"),
    Currency("ang", R.string.currency_country_ang, "nl"),
    Currency("aoa", R.string.currency_country_aoa, "ao"),
    Currency("ars", R.string.currency_country_ars, "ar"),
    Currency("aud", R.string.currency_country_aud, "au"),
    Currency("awg", R.string.currency_country_awg, "aw"),
    Currency("azn", R.string.currency_country_azn, "az"),
    Currency("bam", R.string.currency_country_bam, "ba"),
    Currency("bbd", R.string.currency_country_bbd, "bb"),
    Currency("bch", R.string.currency_country_bch, "bch"),
    Currency("bdt", R.string.currency_country_bdt, "bd"),
    Currency("bgn", R.string.currency_country_bgn, "bg"),
    Currency("bhd", R.string.currency_country_bhd, "bh"),
    Currency("bif", R.string.currency_country_bif, "bi"),
    Currency("bmd", R.string.currency_country_bmd, "bm"),
    Currency("bnd", R.string.currency_country_bnd, "bn"),
    Currency("bob", R.string.currency_country_bob, "bo"),
    Currency("brl", R.string.currency_country_brl, "br"),
    Currency("bsd", R.string.currency_country_bsd, "bs"),
    Currency("btn", R.string.currency_country_btn, "bt"),
    Currency("bwp", R.string.currency_country_bwp, "bw"),
    Currency("byn", R.string.currency_country_byn, "by"),
    Currency("bzd", R.string.currency_country_bzd, "bz"),
    Currency("cad", R.string.currency_country_cad, "ca"),
    Currency("cdf", R.string.currency_country_cdf, "cd"),
    Currency("chf", R.string.currency_country_chf, "ch"),
    Currency("clf", R.string.currency_country_clf, "cl"),
    Currency("clp", R.string.currency_country_clp, "cl"),
    Currency("cnh", R.string.currency_country_cnh, "cn"),
    Currency("cny", R.string.currency_country_cny, "cn"),
    Currency("cop", R.string.currency_country_cop, "co"),
    Currency("crc", R.string.currency_country_crc, "cr"),
    Currency("cup", R.string.currency_country_cup, "cu"),
    Currency("cve", R.string.currency_country_cve, "cv"),
    Currency("czk", R.string.currency_country_czk, "cz"),
    Currency("djf", R.string.currency_country_djf, "dj"),
    Currency("dkk", R.string.currency_country_dkk, "dk"),
    Currency("dop", R.string.currency_country_dop, "do"),
    Currency("dzd", R.string.currency_country_dzd, "dz"),
    Currency("eek", R.string.currency_country_eek, "ee"),
    Currency("egp", R.string.currency_country_egp, "eg"),
    Currency("ern", R.string.currency_country_ern, "er"),
    Currency("etb", R.string.currency_country_etb, "et"),
    Currency("eth", R.string.currency_country_eth, "et"),
    Currency("eur", R.string.currency_country_eur, "eu"),
    Currency("fjd", R.string.currency_country_fjd, "fj"),
    Currency("gbp", R.string.currency_country_gbp, "gb"),
    Currency("gel", R.string.currency_country_gel, "ge"),
    Currency("ghs", R.string.currency_country_ghs, "gh"),
    Currency("gip", R.string.currency_country_gip, "gi"),
    Currency("gmd", R.string.currency_country_gmd, "gm"),
    Currency("gnf", R.string.currency_country_gnf, "gn"),
    Currency("gqe", R.string.currency_country_gqe, "gq"),
    Currency("gtq", R.string.currency_country_gtq, "gt"),
    Currency("gyd", R.string.currency_country_gyd, "gy"),
    Currency("hkd", R.string.currency_country_hkd, "hk"),
    Currency("hnl", R.string.currency_country_hnl, "hn"),
    Currency("hrk", R.string.currency_country_hrk, "hr"),
    Currency("htg", R.string.currency_country_htg, "ht"),
    Currency("huf", R.string.currency_country_huf, "hu"),
    Currency("idr", R.string.currency_country_idr, "id"),
    Currency("ils", R.string.currency_country_ils, "il"),
    Currency("inr", R.string.currency_country_inr, "in"),
    Currency("iqd", R.string.currency_country_iqd, "iq"),
    Currency("irr", R.string.currency_country_irr, "ir"),
    Currency("isk", R.string.currency_country_isk, "is"),
    Currency("jmd", R.string.currency_country_jmd, "jm"),
    Currency("jod", R.string.currency_country_jod, "jo"),
    Currency("jpy", R.string.currency_country_jpy, "jp"),
    Currency("kes", R.string.currency_country_kes, "ke"),
    Currency("kgs", R.string.currency_country_kgs, "kg"),
    Currency("khr", R.string.currency_country_khr, "kh"),
    Currency("kmf", R.string.currency_country_kmf, "km"),
    Currency("kpw", R.string.currency_country_kpw, "kp"),
    Currency("krw", R.string.currency_country_krw, "kr"),
    Currency("kwd", R.string.currency_country_kwd, "kw"),
    Currency("kyd", R.string.currency_country_kyd, "ky"),
    Currency("kzt", R.string.currency_country_kzt, "kz"),
    Currency("lak", R.string.currency_country_lak, "la"),
    Currency("lbp", R.string.currency_country_lbp, "lb"),
    Currency("lkr", R.string.currency_country_lkr, "lk"),
    Currency("lrd", R.string.currency_country_lrd, "lr"),
    Currency("lsl", R.string.currency_country_lsl, "ls"),
    Currency("ltc", R.string.currency_country_ltc, "lt"),
    Currency("lyd", R.string.currency_country_lyd, "ly"),
    Currency("mad", R.string.currency_country_mad, "ma"),
    Currency("mdl", R.string.currency_country_mdl, "md"),
    Currency("mga", R.string.currency_country_mga, "mg"),
    Currency("mkd", R.string.currency_country_mkd, "mk"),
    Currency("mmk", R.string.currency_country_mmk, "mm"),
    Currency("mnt", R.string.currency_country_mnt, "mn"),
    Currency("mop", R.string.currency_country_mop, "mo"),
    Currency("mru", R.string.currency_country_mru, "mr"),
    Currency("mur", R.string.currency_country_mur, "mu"),
    Currency("mvr", R.string.currency_country_mvr, "mv"),
    Currency("mwk", R.string.currency_country_mwk, "mw"),
    Currency("mxn", R.string.currency_country_mxn, "mx"),
    Currency("myr", R.string.currency_country_myr, "my"),
    Currency("mzm", R.string.currency_country_mzm, "mz"),
    Currency("nad", R.string.currency_country_nad, "na"),
    Currency("ngn", R.string.currency_country_ngn, "ng"),
    Currency("nio", R.string.currency_country_nio, "ni"),
    Currency("nok", R.string.currency_country_nok, "no"),
    Currency("npr", R.string.currency_country_npr, "np"),
    Currency("nzd", R.string.currency_country_nzd, "nz"),
    Currency("omr", R.string.currency_country_omr, "om"),
    Currency("pab", R.string.currency_country_pab, "pa"),
    Currency("pen", R.string.currency_country_pen, "pe"),
    Currency("pgk", R.string.currency_country_pgk, "pg"),
    Currency("php", R.string.currency_country_php, "ph"),
    Currency("pkr", R.string.currency_country_pkr, "pk"),
    Currency("pln", R.string.currency_country_pln, "pl"),
    Currency("pyg", R.string.currency_country_pyg, "py"),
    Currency("qar", R.string.currency_country_qar, "qa"),
    Currency("ron", R.string.currency_country_ron, "ro"),
    Currency("rsd", R.string.currency_country_rsd, "rs"),
    Currency("rub", R.string.currency_country_rub, "ru"),
    Currency("rwf", R.string.currency_country_rwf, "rw"),
    Currency("sar", R.string.currency_country_sar, "sa"),
    Currency("sbd", R.string.currency_country_sbd, "sb"),
    Currency("scr", R.string.currency_country_scr, "sc"),
    Currency("sdg", R.string.currency_country_sdg, "sd"),
    Currency("sek", R.string.currency_country_sek, "se"),
    Currency("sgd", R.string.currency_country_sgd, "sg"),
    Currency("shp", R.string.currency_country_shp, "sh"),
    Currency("sll", R.string.currency_country_sll, "sl"),
    Currency("sos", R.string.currency_country_sos, "so"),
    Currency("srd", R.string.currency_country_srd, "sr"),
    Currency("ssp", R.string.currency_country_ssp, "ss"),
    Currency("std", R.string.currency_country_std, "st"),
    Currency("stn", R.string.currency_country_stn, "st"),
    Currency("svc", R.string.currency_country_svc, "sv"),
    Currency("syp", R.string.currency_country_syp, "sy"),
    Currency("szl", R.string.currency_country_szl, "sz"),
    Currency("thb", R.string.currency_country_thb, "th"),
    Currency("tjs", R.string.currency_country_tjs, "tj"),
    Currency("tmt", R.string.currency_country_tmt, "tm"),
    Currency("tnd", R.string.currency_country_tnd, "tn"),
    Currency("top", R.string.currency_country_top, "to"),
    Currency("try", R.string.currency_country_try, "tr"),
    Currency("ttd", R.string.currency_country_ttd, "tt"),
    Currency("twd", R.string.currency_country_twd, "tw"),
    Currency("tzs", R.string.currency_country_tzs, "tz"),
    Currency("uah", R.string.currency_country_uah, "ua"),
    Currency("ugx", R.string.currency_country_ugx, "ug"),
    Currency("usd", R.string.currency_country_usd, "us"),
    Currency("uyu", R.string.currency_country_uyu, "uy"),
    Currency("uzs", R.string.currency_country_uzs, "uz"),
    Currency("vef", R.string.currency_country_vef, "ve"),
    Currency("vnd", R.string.currency_country_vnd, "vn"),
    Currency("vuv", R.string.currency_country_vuv, "vu"),
    Currency("wst", R.string.currency_country_wst, "ws"),
    Currency("xaf", R.string.currency_country_xaf, "cf"),
    Currency("xcd", R.string.currency_country_xcd, "gd"),
    Currency("xof", R.string.currency_country_xof, "ne"),
    Currency("yer", R.string.currency_country_yer, "ye"),
    Currency("zar", R.string.currency_country_zar, "za"),
    Currency("zmw", R.string.currency_country_zmw, "zm")
)
